/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class DanhMucBanh extends javax.swing.JFrame {

    boolean isAdding = false;
    /**
     * Creates new form DanhMucBanh
     */
    public DanhMucBanh() {
        initComponents();
        ChangeText("-","","","","");
        this.setLocationRelativeTo(null);
    }
    
    public void ChangeText(String ma, String Ten, String DG, String SL, String NCC){
        this.MaBanh.setText(ma);
        this.TenBanh.setText(Ten);
        this.DonGia.setText(DG);
        this.SoLuong.setText(SL);
        this.buttSuaBanh.setEnabled(false);
        this.buttXoaBanh.setEnabled(false);
    }
    
    public void ChuThich(){
        this.TenBanh.setText("Tên bánh");
        this.DonGia.setText("Đơn giá");
        this.SoLuong.setText("Số lượng");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel = new javax.swing.JPanel();
        lblDanhMucBanh = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPaneDSB = new javax.swing.JScrollPane();
        DSBanh = new javax.swing.JTable();
        jPanelCTB = new javax.swing.JPanel();
        lblMaBanh = new javax.swing.JLabel();
        lblTenBanh = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        lblDonGia = new javax.swing.JLabel();
        buttThemBanh = new javax.swing.JButton();
        buttXoaBanh = new javax.swing.JButton();
        buttSuaBanh = new javax.swing.JButton();
        MaBanh = new javax.swing.JLabel();
        SoLuong = new javax.swing.JTextField();
        DonGia = new javax.swing.JTextField();
        TenBanh = new javax.swing.JTextField();
        jPanelTK = new javax.swing.JPanel();
        buttTK = new javax.swing.JButton();
        NoiDungTK = new javax.swing.JTextField();
        buttNhapBanh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Danh mục bánh");
        setAutoRequestFocus(false);
        setMaximumSize(new java.awt.Dimension(2048, 2048));
        setMinimumSize(new java.awt.Dimension(950, 440));
        setPreferredSize(new java.awt.Dimension(900, 400));

        jPanel.setLayout(new java.awt.GridBagLayout());

        lblDanhMucBanh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDanhMucBanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/cake.png"))); // NOI18N
        lblDanhMucBanh.setText("DANH MỤC BÁNH");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel.add(lblDanhMucBanh, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 855;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 10);
        jPanel.add(jSeparator1, gridBagConstraints);

        jScrollPaneDSB.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách"));

        DSBanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã bánh", "Tên bánh", "Đơn giá", "Nhà cung cấp", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DSBanh.setColumnSelectionAllowed(true);
        DSBanh.getTableHeader().setReorderingAllowed(false);
        jScrollPaneDSB.setViewportView(DSBanh);
        DSBanh.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 474;
        gridBagConstraints.ipady = 246;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 0);
        jPanel.add(jScrollPaneDSB, gridBagConstraints);

        jPanelCTB.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết bánh"));
        jPanelCTB.setLayout(new java.awt.GridBagLayout());

        lblMaBanh.setText("Mã bánh:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(21, 36, 0, 0);
        jPanelCTB.add(lblMaBanh, gridBagConstraints);

        lblTenBanh.setText("Tên bánh:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(21, 36, 0, 0);
        jPanelCTB.add(lblTenBanh, gridBagConstraints);

        lblSoLuong.setText("Số lượng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(21, 36, 0, 0);
        jPanelCTB.add(lblSoLuong, gridBagConstraints);

        lblDonGia.setText("Đơn giá:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(21, 36, 0, 0);
        jPanelCTB.add(lblDonGia, gridBagConstraints);

        buttThemBanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/cake_plus.png"))); // NOI18N
        buttThemBanh.setText("Thêm");
        buttThemBanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttThemBanhActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(21, 30, 0, 0);
        jPanelCTB.add(buttThemBanh, gridBagConstraints);

        buttXoaBanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/cake_minus.png"))); // NOI18N
        buttXoaBanh.setText("Xóa");
        buttXoaBanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttXoaBanhActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(21, 30, 0, 0);
        jPanelCTB.add(buttXoaBanh, gridBagConstraints);

        buttSuaBanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/cake_pencil.png"))); // NOI18N
        buttSuaBanh.setText("Sửa");
        buttSuaBanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttSuaBanhActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(21, 30, 0, 30);
        jPanelCTB.add(buttSuaBanh, gridBagConstraints);

        MaBanh.setText("BN004");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 36, 0, 0);
        jPanelCTB.add(MaBanh, gridBagConstraints);

        SoLuong.setEnabled(false);
        SoLuong.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SoLuongFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 36, 0, 0);
        jPanelCTB.add(SoLuong, gridBagConstraints);

        DonGia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DonGiaFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 36, 0, 0);
        jPanelCTB.add(DonGia, gridBagConstraints);

        TenBanh.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TenBanhCaretUpdate(evt);
            }
        });
        TenBanh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TenBanhFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 36, 0, 0);
        jPanelCTB.add(TenBanh, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        jPanel.add(jPanelCTB, gridBagConstraints);

        jPanelTK.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));
        jPanelTK.setLayout(new java.awt.GridBagLayout());

        buttTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/search.png"))); // NOI18N
        buttTK.setText("Tìm kiếm");
        buttTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttTKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 6, 0);
        jPanelTK.add(buttTK, gridBagConstraints);

        NoiDungTK.setMinimumSize(new java.awt.Dimension(200, 20));
        NoiDungTK.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        jPanelTK.add(NoiDungTK, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel.add(jPanelTK, gridBagConstraints);

        buttNhapBanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/cake_arrow.png"))); // NOI18N
        buttNhapBanh.setText("Nhập bánh");
        buttNhapBanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttNhapBanhActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel.add(buttNhapBanh, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 876, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttThemBanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttThemBanhActionPerformed
        if(isAdding == false)
        {
            //Tự lấy mã bánh tiếp theo??
            this.MaBanh.setText("??");
            isAdding = true;
            this.SoLuong.setEnabled(true);
            ChuThich();
            this.buttSuaBanh.setEnabled(false);
            this.buttXoaBanh.setEnabled(false);
        }
        else
        {
            //thêm bánh
            this.SoLuong.setEnabled(false);
            this.buttSuaBanh.setEnabled(true);
            this.buttXoaBanh.setEnabled(true);
        }
    }//GEN-LAST:event_buttThemBanhActionPerformed

    private void buttXoaBanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttXoaBanhActionPerformed
        int reply = JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn xóa bánh này?","Xóa bánh",JOptionPane.WARNING_MESSAGE);
        if(reply == JOptionPane.YES_OPTION){
            //xóa bánh
        }
    }//GEN-LAST:event_buttXoaBanhActionPerformed

    private void buttSuaBanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttSuaBanhActionPerformed
        //sửa bánh
    }//GEN-LAST:event_buttSuaBanhActionPerformed

    private void TenBanhFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TenBanhFocusGained
        this.TenBanh.setText("");
    }//GEN-LAST:event_TenBanhFocusGained

    private void SoLuongFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SoLuongFocusGained
        this.SoLuong.setText("");
    }//GEN-LAST:event_SoLuongFocusGained

    private void DonGiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DonGiaFocusGained
        this.DonGia.setText("");
    }//GEN-LAST:event_DonGiaFocusGained

    private void buttTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttTKActionPerformed
        String tukhoa = this.NoiDungTK.getText();
        //tìm kiếm
    }//GEN-LAST:event_buttTKActionPerformed

    private void TenBanhCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TenBanhCaretUpdate
        if(!isAdding)
        {
         // enable xoa and sua button
        }
    }//GEN-LAST:event_TenBanhCaretUpdate

    private void buttNhapBanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttNhapBanhActionPerformed
        new LapPhieuNhap().setVisible(true);
    }//GEN-LAST:event_buttNhapBanhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhMucBanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhMucBanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhMucBanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhMucBanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhMucBanh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DSBanh;
    private javax.swing.JTextField DonGia;
    private javax.swing.JLabel MaBanh;
    private javax.swing.JTextField NoiDungTK;
    private javax.swing.JTextField SoLuong;
    private javax.swing.JTextField TenBanh;
    private javax.swing.JButton buttNhapBanh;
    private javax.swing.JButton buttSuaBanh;
    private javax.swing.JButton buttTK;
    private javax.swing.JButton buttThemBanh;
    private javax.swing.JButton buttXoaBanh;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanelCTB;
    private javax.swing.JPanel jPanelTK;
    private javax.swing.JScrollPane jScrollPaneDSB;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDanhMucBanh;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblMaBanh;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenBanh;
    // End of variables declaration//GEN-END:variables
}
