/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BUS.BUSQLHOADON;
import BUS.BUSQLSANPHAM;
import BUS.ExportPDF;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.DocumentException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import static java.time.Instant.now;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import qlbh.SANPHAM;
/**
 *
 * @author Admin
 */
public class QuanLyHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyHoaDon
     */
    
    boolean isShowing = false;
    private  float Tongtien;
    
    private DefaultTableModel tableModelHD;
    private String[] colsName = {"STT", "Mã HD", "Tên KH", "Tên NV", "Ngày lập", "Tổng tiền"};
    private DefaultTableModel tableModelCT;
    private String[] colsNameCT = {"STT", "Mã SP", "Tên SP","SL Mua","Thành tiền"};
    
    ArrayList<SANPHAM> al;
    ArrayList<String[]> alrow;
    ArrayList<String[]> alrowCT;
    DateFormat dateFormat;
    
    public static int mahd =-1;
    public QuanLyHoaDon() {
        initComponents();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        this.setLocationRelativeTo(null);
        LamMoi();
        tableModelHD = new DefaultTableModel();
        tableModelHD.setColumnIdentifiers(colsName);
        JtableHD.setModel(tableModelHD);
        
        tableModelCT = new DefaultTableModel();
        tableModelCT.setColumnIdentifiers(colsNameCT);
        JtableCTHD.setModel(tableModelCT);
        
        DisableComponent();
    }
   
    public void LamMoiTTHD(String mahd, String makh, String manv, String tenkh, String tennv, Date ngl, String tgt){
        this.lbMaHD.setText(mahd);
        this.txbMaKH.setText(makh);
        this.txbMaNV.setText(manv);
        this.txbTenKH.setText(tenkh);
        this.txbTenNV.setText(tennv);
        this.dpNgayHD.setDate(ngl);
        this.lbTong.setText(tgt);
    }
    
    public void LamMoiCTHD(String dg, String sl){
        txbDG.setText(dg);
        txbSL.setText(sl);
    }
    
    public void LamMoi(){
        
        LamMoiTTHD("-","","","","",new Date(), "");
        LamMoiCTHD("","");
        this.txbSearch.setText("");
    }
    
    public void DisableComponent()
    {
        this.btnAdd.setEnabled(false);
        this.btnDel.setEnabled(false);
        this.btnUpdate.setEnabled(false);
    }
    
    public void EnableComponent()
    {
        this.btnAdd.setEnabled(true);
        this.btnDel.setEnabled(true);
        this.btnUpdate.setEnabled(true);
    }
    
    public void LoadButton()
    {
            this.btnIn.setEnabled(!isShowing);
            this.btnLapHD.setEnabled(!isShowing);
            this.btnSua.setEnabled(!isShowing);
            this.btnXoa.setEnabled(!isShowing);
            this.btnAdd.setEnabled(!isShowing);
            this.btnDel.setEnabled(!isShowing);
            this.btnUpdate.setEnabled(!isShowing);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScollHD = new javax.swing.JScrollPane();
        JtableHD = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtableCTHD = new javax.swing.JTable();
        jpanelCTHD = new javax.swing.JPanel();
        lblTenSP = new javax.swing.JLabel();
        lblDonGia = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txbDG = new javax.swing.JTextField();
        txbSL = new javax.swing.JTextField();
        txbTenSP = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblMaHD = new javax.swing.JLabel();
        lblNgayLap = new javax.swing.JLabel();
        lblMaKH = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        lblTenKH = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        btnIn = new javax.swing.JButton();
        lblTong = new javax.swing.JLabel();
        txbMaKH = new javax.swing.JTextField();
        txbMaNV = new javax.swing.JTextField();
        txbTenKH = new javax.swing.JTextField();
        txbTenNV = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        lbTong = new javax.swing.JLabel();
        lbMaHD = new javax.swing.JLabel();
        dpNgayHD = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        btnLapHD = new javax.swing.JButton();
        lblQuanLyHD = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        txbSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý hóa đơn");
        setAutoRequestFocus(false);
        setResizable(false);

        jScollHD.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách hóa đơn"));

        JtableHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JtableHD.getTableHeader().setReorderingAllowed(false);
        JtableHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtableHDMousePressed(evt);
            }
        });
        jScollHD.setViewportView(JtableHD);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết hóa đơn"));
        jScrollPane2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        JtableCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JtableCTHD.getTableHeader().setReorderingAllowed(false);
        JtableCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtableCTHDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JtableCTHD);

        jpanelCTHD.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));
        jpanelCTHD.setAutoscrolls(true);
        jpanelCTHD.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jpanelCTHD.setLayout(new java.awt.GridBagLayout());

        lblTenSP.setText("Tên sản phẩm:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(190, 200, 0, 0);
        jpanelCTHD.add(lblTenSP, gridBagConstraints);

        lblDonGia.setText("Đơn giá:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(188, 118, 0, 0);
        jpanelCTHD.add(lblDonGia, gridBagConstraints);

        lblSoLuong.setText("Số lượng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 110, 0, 0);
        jpanelCTHD.add(lblSoLuong, gridBagConstraints);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/file_add.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(13, 196, 163, 0);
        jpanelCTHD.add(btnAdd, gridBagConstraints);

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/file_del.png"))); // NOI18N
        btnDel.setText("Xóa");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 10, 163, 0);
        jpanelCTHD.add(btnDel, gridBagConstraints);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/file_edit.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(13, 25, 163, 0);
        jpanelCTHD.add(btnUpdate, gridBagConstraints);

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/crossout.png"))); // NOI18N
        btnCancel.setText("Hủy bỏ");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 20, 163, 0);
        jpanelCTHD.add(btnCancel, gridBagConstraints);

        txbDG.setEditable(false);
        txbDG.setText("000");
        txbDG.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(185, 18, 0, 196);
        jpanelCTHD.add(txbDG, gridBagConstraints);

        txbSL.setText("100");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 196);
        jpanelCTHD.add(txbSL, gridBagConstraints);

        txbTenSP.setEditable(false);
        txbTenSP.setMinimumSize(new java.awt.Dimension(300, 20));
        txbTenSP.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        jpanelCTHD.add(txbTenSP, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa đơn"));
        jPanel2.setAutoscrolls(true);
        jPanel2.setMinimumSize(new java.awt.Dimension(471, 322));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        lblMaHD.setText("Mã hóa đơn:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(11, 16, 0, 0);
        jPanel2.add(lblMaHD, gridBagConstraints);

        lblNgayLap.setText("Ngày lập:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(11, 58, 0, 0);
        jPanel2.add(lblNgayLap, gridBagConstraints);

        lblMaKH.setText("Mã khách hàng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(30, 16, 0, 0);
        jPanel2.add(lblMaKH, gridBagConstraints);

        lblMaNV.setText("Mã nhân viên:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(30, 16, 0, 0);
        jPanel2.add(lblMaNV, gridBagConstraints);

        lblTenKH.setText("Tên khách hàng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(30, 16, 0, 0);
        jPanel2.add(lblTenKH, gridBagConstraints);

        lblTenNV.setText("Tên nhân viên:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(30, 16, 0, 0);
        jPanel2.add(lblTenNV, gridBagConstraints);

        btnIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/printButton.png"))); // NOI18N
        btnIn.setText("In");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 18, 6, 0);
        jPanel2.add(btnIn, gridBagConstraints);

        lblTong.setText("Tổng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 48, 0, 0);
        jPanel2.add(lblTong, gridBagConstraints);

        txbMaKH.setEditable(false);
        txbMaKH.setText("KH002");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 15, 0, 0);
        jPanel2.add(txbMaKH, gridBagConstraints);

        txbMaNV.setEditable(false);
        txbMaNV.setText("NV004");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 15, 0, 0);
        jPanel2.add(txbMaNV, gridBagConstraints);

        txbTenKH.setEditable(false);
        txbTenKH.setText("Thảo lé aaa aaaloha ahihi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 15, 0, 10);
        jPanel2.add(txbTenKH, gridBagConstraints);

        txbTenNV.setEditable(false);
        txbTenNV.setText("Thảo lé aaa aaaloha ahihi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 15, 0, 10);
        jPanel2.add(txbTenNV, gridBagConstraints);

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/del.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 18, 6, 0);
        jPanel2.add(btnXoa, gridBagConstraints);

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/edit_16.gif"))); // NOI18N
        btnSua.setText("Cập nhật");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 18, 6, 0);
        jPanel2.add(btnSua, gridBagConstraints);

        lbTong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTong.setText("5000000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 18, 0, 0);
        jPanel2.add(lbTong, gridBagConstraints);

        lbMaHD.setText("HD001");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(11, 15, 0, 0);
        jPanel2.add(lbMaHD, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        jPanel2.add(dpNgayHD, gridBagConstraints);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        btnLapHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/forum_add.png"))); // NOI18N
        btnLapHD.setText("Lập hóa đơn");
        btnLapHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapHDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(6, -50, 0, 30);
        jPanel5.add(btnLapHD, gridBagConstraints);

        lblQuanLyHD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQuanLyHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/forum.png"))); // NOI18N
        lblQuanLyHD.setText("QUẢN LÝ HÓA ĐƠN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        jPanel5.add(lblQuanLyHD, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1096;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 10);
        jPanel5.add(jSeparator2, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm hóa đơn"));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/search.png"))); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 6, 0);
        jPanel4.add(btnSearch, gridBagConstraints);

        txbSearch.setMinimumSize(new java.awt.Dimension(300, 20));
        txbSearch.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        jPanel4.add(txbSearch, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScollHD, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpanelCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScollHD, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanelCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        LamMoiCTHD("","");
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnLapHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapHDActionPerformed
       isShowing = true;
       ThemHoaDon formThemHD = new ThemHoaDon();
       formThemHD.addWindowListener( new WindowAdapter() {
                    @Override
                    public void windowClosed(WindowEvent we) {
                        btnSearchActionPerformed(evt);
                        clearCTHD();
                        isShowing = false;
                        LoadButton();
                    }
                } );
       LoadButton();
       formThemHD.show();
    }//GEN-LAST:event_btnLapHDActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        try {
            try {
                if(alrow!=null && ExportPDF.getInstance().ExportHD(alrow))
                {
                    JOptionPane.showMessageDialog(null, "Xuất file thành công", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Thất bại!", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (DocumentException ex) {
                Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
       //sửa hóa đơn
       if(JtableHD.getSelectedRow() == -1)
       {
           JOptionPane.showMessageDialog(null, "Vui lòng chọn thông tin muốn sửa!", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
       }
       else
       {
           Date date = this.dpNgayHD.getDate();
           java.sql.Date sqlDate = new java.sql.Date(date.getTime());
           if(BUSQLHOADON.getInstance().Update(mahd, sqlDate))
           {
               JOptionPane.showMessageDialog(null, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
               btnSearchActionPerformed(evt);
           }
           else{
               JOptionPane.showMessageDialog(null, "Sửa thất bại!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
           }
       }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       // xóa hóa đơn
       if(JtableHD.getSelectedRow() == -1)
       {
           JOptionPane.showMessageDialog(null, "Vui lòng chọn thông tin muốn xóa!", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
       }
       else
       {
           int reply = JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn xóa hóa đơn này?","Xóa hóa đơn",JOptionPane.WARNING_MESSAGE);
           if(reply == JOptionPane.YES_OPTION){
            //xóa hđ        
            if(BUSQLHOADON.getInstance().Delete(mahd))
           {
               JOptionPane.showMessageDialog(null, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
               btnSearchActionPerformed(evt);
           }
           else{
               JOptionPane.showMessageDialog(null, "Xóa thất bại!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
           }  
        }
       }
    }//GEN-LAST:event_btnXoaActionPerformed

    public void clearCTHD()
    {
        tableModelCT = new DefaultTableModel();
        tableModelCT.setColumnIdentifiers(colsNameCT);
        JtableCTHD.setModel(tableModelCT);
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //thêm cthd
        isShowing = true;
       ThemCTHD formThemCTHD = new ThemCTHD();
       formThemCTHD.addWindowListener( new WindowAdapter() {
                    @Override
                    public void windowClosed(WindowEvent we) {
                        LoadCTHD(mahd);
                        isShowing = false;
                        if(BUSQLHOADON.getInstance().UpdateTT(mahd, Tongtien))
                        {
                            JOptionPane.showMessageDialog(null, "Load thành công", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
                        }
                        LoadButton();
                        btnSearchActionPerformed(evt);
                    }
                } );
       LoadButton();
       formThemCTHD.show();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
       if (JtableCTHD.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn thông tin muốn xóa!", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int reply = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa?", "Xóa chi tiết hóa đơn", JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                //xóa cthd    
                int row = JtableCTHD.getSelectedRow();
                int masp = Integer.parseInt(JtableCTHD.getModel().getValueAt(row, 1).toString());
                if (BUSQLHOADON.getInstance().DeleteCTHD(mahd, masp)) {
                    JOptionPane.showMessageDialog(null, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    LoadCTHD(mahd);
                    if(BUSQLHOADON.getInstance().UpdateTT(mahd, Tongtien))
                        {
                            JOptionPane.showMessageDialog(null, "Load thành công", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
                        }
                        LoadButton();
                    btnSearchActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa thất bại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // sửa hóa đơn
        if (JtableCTHD.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn thông tin muốn sửa!", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int reply = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn sửa?", "Sửa chi tiết hóa đơn", JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                //xóa cthd    
                int row = JtableCTHD.getSelectedRow();
                int masp = Integer.parseInt(JtableCTHD.getModel().getValueAt(row, 1).toString());
                int sl = Integer.parseInt(txbSL.getText());
                if (BUSQLHOADON.getInstance().UpdateCTHD(mahd, masp, sl)) {
                    JOptionPane.showMessageDialog(null, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    LoadCTHD(mahd);
                    if(BUSQLHOADON.getInstance().UpdateTT(mahd, Tongtien))
                        {
                            JOptionPane.showMessageDialog(null, "Load thành công", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
                        }
                        LoadButton();
                    btnSearchActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(null, "Sửa thất bại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
            LamMoiCTHD("","");
            this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        //tìm kiếm
        tableModelHD.setRowCount(0);

        alrow = BUSQLHOADON.getInstance().SearchSP(txbSearch.getText());
        if (alrow != null) {
            Object count = 1;
            for (int i = 0; i < alrow.size(); i++) {
                String rows[] = new String[8];
                rows[0] = count.toString();                    //STT
                rows[1] = alrow.get(i)[0];                     //MaHD
                rows[2] = alrow.get(i)[1];                     //TenKH
                rows[3] = alrow.get(i)[2];                     //TENNV
                rows[4] = alrow.get(i)[3];                     //NgayHD
                rows[5] = alrow.get(i)[4];                     //Tổng tiền
                tableModelHD.addRow(rows);
                //mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update lại trên frame
                count = (int)count + 1;
            }
        }
         DisableComponent();
         clearCTHD();
         LamMoi();
    }//GEN-LAST:event_btnSearchActionPerformed

    public void LoadCTHD(int mahd)
    {
        Tongtien = 0;
        tableModelCT.setRowCount(0);
       
        alrowCT = BUSQLHOADON.getInstance().SearchCT(mahd);
      
        if (alrowCT != null) {
            Object count = 1;
            for (int i = 0; i < alrowCT.size(); i++) {
                String rows[] = new String[5];
                rows[0] = count.toString();                      //STT
                rows[1] = alrowCT.get(i)[0];                     //MaSP
                rows[2] = alrowCT.get(i)[1];                     //TenSP
                rows[3] = alrowCT.get(i)[2];                     //SLMUA
                int sl = Integer.parseInt(alrowCT.get(i)[2]);
                float dg = Float.parseFloat(alrowCT.get(i)[3]);
                Object tt = sl * dg;
                rows[4] = tt.toString();                         //Tổng tiền
                tableModelCT.addRow(rows);
                //mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update lại trên frame
                count = (int)count + 1;
                Tongtien += (float)tt;
            }
        }
    }
    
    private void JtableCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableCTHDMouseClicked
        int row = JtableCTHD.getSelectedRow();
        this.txbTenSP.setText(JtableCTHD.getModel().getValueAt(row, 2).toString());
        this.txbSL.setText(JtableCTHD.getModel().getValueAt(row, 3).toString());
        this.txbDG.setText(alrowCT.get(row)[3]);
    }//GEN-LAST:event_JtableCTHDMouseClicked

    private void JtableHDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableHDMousePressed
        // TODO add your handling code here:
        int row = JtableHD.getSelectedRow();
        lbMaHD.setText(JtableHD.getModel().getValueAt(row, 1).toString());
        txbTenKH.setText(JtableHD.getModel().getValueAt(row, 2).toString());
        txbTenNV.setText(JtableHD.getModel().getValueAt(row, 3).toString());
        //dpNgayHD.setDateFormatString(JtableHD.getModel().getValueAt(row, 4).toString());
        lbTong.setText(JtableHD.getModel().getValueAt(row, 5).toString());
        txbMaKH.setText(alrow.get(row)[5]);
        txbMaNV.setText(alrow.get(row)[6]);
        
        mahd = Integer.parseInt(alrow.get(row)[0]);
        EnableComponent();
        LoadCTHD(mahd);
    }//GEN-LAST:event_JtableHDMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableCTHD;
    private javax.swing.JTable JtableHD;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnLapHD;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnXoa;
    private com.toedter.calendar.JDateChooser dpNgayHD;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScollHD;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpanelCTHD;
    private javax.swing.JLabel lbMaHD;
    private javax.swing.JLabel lbTong;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblMaHD;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblNgayLap;
    private javax.swing.JLabel lblQuanLyHD;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblTong;
    private javax.swing.JTextField txbDG;
    private javax.swing.JTextField txbMaKH;
    private javax.swing.JTextField txbMaNV;
    private javax.swing.JTextField txbSL;
    private javax.swing.JTextField txbSearch;
    private javax.swing.JTextField txbTenKH;
    private javax.swing.JTextField txbTenNV;
    private javax.swing.JTextField txbTenSP;
    // End of variables declaration//GEN-END:variables
}
