/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BUS.BUSQLPHIEUNHAP;
import BUS.ExportPDF;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.DocumentException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import qlbh.SANPHAM;
/**
 *
 * @author Admin
 */
public class QuanLyPhieuNhap extends javax.swing.JFrame {

    boolean isShowing = false;
    private  float Tongtien;
    
    private DefaultTableModel tableModelPN;
    private String[] colsName = {"STT","Mã PN", "Mã NV", "Tên NV", "Ngày nhập","Nhà cung cấp", "Tổng tiền"};
    private DefaultTableModel tableModelCT;
    private String[] colsNameCT = {"STT","Mã SP", "Tên SP", "SL Nhập", "Thành tiền"};
    
    ArrayList<SANPHAM> al;
    ArrayList<String[]> alrow;
    ArrayList<String[]> alrowCT;
    DateFormat dateFormat;
    
    public static int mapn =-1;
    public QuanLyPhieuNhap() {
        initComponents();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        this.setLocationRelativeTo(null);
        ClearCom();
        tableModelPN = new DefaultTableModel();
        tableModelPN.setColumnIdentifiers(colsName);
        JtablePN.setModel(tableModelPN);
        
        tableModelCT = new DefaultTableModel();
        tableModelCT.setColumnIdentifiers(colsNameCT);
        JtableCTPN.setModel(tableModelCT);
        
        DisableComponent();
    }
   
    public void ClearPN(){
        this.lbMa.setText("NA");
        this.txbMaNV.setText("NA");
        this.txbTenNV.setText("");
        this.dpNgayNhap.setDate(new Date());
        this.lbTong.setText("");
    }
    
    public void tableCT()
    {
        tableModelCT = new DefaultTableModel();
        tableModelCT.setColumnIdentifiers(colsNameCT);
        JtableCTPN.setModel(tableModelCT);
    }
    
    public void ClearCTPN(){
        txbDG.setText("");
        txbSL.setText("");
    }
    
    public void ClearCom(){
        
        ClearPN();
        ClearCTPN();
        this.txbSearch.setText("");
    }
    
    public void DisableComponent()
    {
        this.btnAdd.setEnabled(false);
        this.btnDel.setEnabled(false);
        this.btnUp.setEnabled(false);
    }
    
    public void EnableComponent()
    {
        this.btnAdd.setEnabled(true);
        this.btnDel.setEnabled(true);
        this.btnUp.setEnabled(true);
    }
    
    public void LoadButton()
    {
            this.btnIn.setEnabled(!isShowing);
            this.btnLapPN.setEnabled(!isShowing);
            this.btnSua.setEnabled(!isShowing);
            this.btnXoa.setEnabled(!isShowing);
            this.btnAdd.setEnabled(!isShowing);
            this.btnDel.setEnabled(!isShowing);
            this.btnUp.setEnabled(!isShowing);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        JtablePN = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtableCTPN = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblTenSP = new javax.swing.JLabel();
        lblDonGia = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnUp = new javax.swing.JButton();
        txbDG = new javax.swing.JTextField();
        txbSL = new javax.swing.JTextField();
        txbTenSP = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblMaPN = new javax.swing.JLabel();
        lblNgayNhap = new javax.swing.JLabel();
        lblNCC = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        btnIn = new javax.swing.JButton();
        lblTong = new javax.swing.JLabel();
        txbMaNV = new javax.swing.JTextField();
        txbTenNV = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        lbTong = new javax.swing.JLabel();
        lbMa = new javax.swing.JLabel();
        cbNCC = new javax.swing.JComboBox<>();
        dpNgayNhap = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        btnLapPN = new javax.swing.JButton();
        lblQuanLyPN = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        txbSearch = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý phiếu nhập");
        setAutoRequestFocus(false);
        setResizable(false);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách phiếu nhập"));

        JtablePN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JtablePN.getTableHeader().setReorderingAllowed(false);
        JtablePN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtablePNMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(JtablePN);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết phiếu nhập"));
        jScrollPane2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        JtableCTPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JtableCTPN.getTableHeader().setReorderingAllowed(false);
        JtableCTPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtableCTPNMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JtableCTPN);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));
        jPanel1.setAutoscrolls(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblTenSP.setText("Tên sản phẩm:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel1.add(lblTenSP, gridBagConstraints);

        lblDonGia.setText("Đơn giá:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel1.add(lblDonGia, gridBagConstraints);

        lblSoLuong.setText("Số lượng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 14, 10, 68);
        jPanel1.add(lblSoLuong, gridBagConstraints);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/file_add.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(45, 0, 0, 0);
        jPanel1.add(btnAdd, gridBagConstraints);

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/file_del.png"))); // NOI18N
        btnDel.setText("Xóa");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(45, 100, 0, 0);
        jPanel1.add(btnDel, gridBagConstraints);

        btnUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/file_edit.png"))); // NOI18N
        btnUp.setText("Sửa");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(45, -35, 0, 0);
        jPanel1.add(btnUp, gridBagConstraints);

        txbDG.setEditable(false);
        txbDG.setText("50000");
        txbDG.setToolTipText("");
        txbDG.setMinimumSize(new java.awt.Dimension(100, 22));
        txbDG.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 7, 0);
        jPanel1.add(txbDG, gridBagConstraints);

        txbSL.setText("0");
        txbSL.setMinimumSize(new java.awt.Dimension(60, 22));
        txbSL.setPreferredSize(new java.awt.Dimension(60, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 7, 0);
        jPanel1.add(txbSL, gridBagConstraints);

        txbTenSP.setEnabled(false);
        txbTenSP.setMinimumSize(new java.awt.Dimension(300, 20));
        txbTenSP.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 10, 0);
        jPanel1.add(txbTenSP, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Phiếu nhập"));
        jPanel2.setAutoscrolls(true);
        jPanel2.setMinimumSize(new java.awt.Dimension(471, 322));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        lblMaPN.setText("Mã phiếu nhập:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(11, 16, 0, 0);
        jPanel2.add(lblMaPN, gridBagConstraints);

        lblNgayNhap.setText("Ngày nhập:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(11, 58, 0, 0);
        jPanel2.add(lblNgayNhap, gridBagConstraints);

        lblNCC.setText("Nhà cung cấp:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(30, 16, 0, 0);
        jPanel2.add(lblNCC, gridBagConstraints);

        lblMaNV.setText("Mã nhân viên:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(30, 16, 0, 0);
        jPanel2.add(lblMaNV, gridBagConstraints);

        lblTenNV.setText("Tên nhân viên:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(30, 16, 0, 0);
        jPanel2.add(lblTenNV, gridBagConstraints);

        btnIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/printButton.png"))); // NOI18N
        btnIn.setText("In");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 18, 6, 0);
        jPanel2.add(btnIn, gridBagConstraints);

        lblTong.setText("Tổng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 48, 0, 0);
        jPanel2.add(lblTong, gridBagConstraints);

        txbMaNV.setEditable(false);
        txbMaNV.setMinimumSize(new java.awt.Dimension(43, 22));
        txbMaNV.setName(""); // NOI18N
        txbMaNV.setPreferredSize(new java.awt.Dimension(43, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 15, 0, 0);
        jPanel2.add(txbMaNV, gridBagConstraints);

        txbTenNV.setEditable(false);
        txbTenNV.setMinimumSize(new java.awt.Dimension(170, 22));
        txbTenNV.setPreferredSize(new java.awt.Dimension(170, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 15, 0, 10);
        jPanel2.add(txbTenNV, gridBagConstraints);

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/del.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 18, 6, 0);
        jPanel2.add(btnXoa, gridBagConstraints);

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/edit_16.gif"))); // NOI18N
        btnSua.setText("Cập nhật");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 18, 6, 0);
        jPanel2.add(btnSua, gridBagConstraints);

        lbTong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTong.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 18, 0, 0);
        jPanel2.add(lbTong, gridBagConstraints);

        lbMa.setText("NA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(11, 15, 0, 0);
        jPanel2.add(lbMa, gridBagConstraints);

        cbNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABC", "XYZ", "BCS", "TTT" }));
        cbNCC.setMinimumSize(new java.awt.Dimension(130, 22));
        cbNCC.setPreferredSize(new java.awt.Dimension(130, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(27, 15, 0, 10);
        jPanel2.add(cbNCC, gridBagConstraints);

        dpNgayNhap.setMinimumSize(new java.awt.Dimension(170, 22));
        dpNgayNhap.setPreferredSize(new java.awt.Dimension(170, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 10);
        jPanel2.add(dpNgayNhap, gridBagConstraints);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        btnLapPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/forum_add.png"))); // NOI18N
        btnLapPN.setText("Lập phiếu nhập");
        btnLapPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapPNActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipady = 9;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel5.add(btnLapPN, gridBagConstraints);

        lblQuanLyPN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQuanLyPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/forum.png"))); // NOI18N
        lblQuanLyPN.setText("QUẢN LÝ PHIẾU NHẬP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        jPanel5.add(lblQuanLyPN, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1096;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 10);
        jPanel5.add(jSeparator2, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm phiếu nhập"));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/search.png"))); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 6, 0);
        jPanel4.add(btnSearch, gridBagConstraints);

        txbSearch.setMinimumSize(new java.awt.Dimension(300, 20));
        txbSearch.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        jPanel4.add(txbSearch, gridBagConstraints);

        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library/crossout.png"))); // NOI18N
        btnHuy.setText("Thoát");
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnHuyMouseClicked

    private void btnLapPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapPNActionPerformed
        isShowing = true;
       ThemPhieuNhap formThemPN = new ThemPhieuNhap();
       formThemPN.addWindowListener( new WindowAdapter() {
                    @Override
                    public void windowClosed(WindowEvent we) {
                        btnSearchActionPerformed(evt);
                        ClearCTPN();
                        isShowing = false;
                        LoadButton();
                    }
                } );
       LoadButton();
       formThemPN.show();
    }//GEN-LAST:event_btnLapPNActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        try {          
            try {
                if(alrow!=null && ExportPDF.getInstance().ExportPN(alrow))
                {
                    JOptionPane.showMessageDialog(null, "Xuất file thành công", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Thất bại!", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (DocumentException ex) {
                Logger.getLogger(QuanLyPhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(QuanLyPhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
       //sửa PN
       //sửa hóa đơn
       if(JtablePN.getSelectedRow() == -1)
       {
           JOptionPane.showMessageDialog(null, "Vui lòng chọn thông tin muốn sửa!", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
       }
       else
       {
           Date date = this.dpNgayNhap.getDate();
           java.sql.Date sqlDate = new java.sql.Date(date.getTime());
           if(BUSQLPHIEUNHAP.getInstance().Update(mapn, sqlDate, cbNCC.getSelectedItem().toString()))
           {
               JOptionPane.showMessageDialog(null, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
               btnSearchActionPerformed(evt);
           }
           else{
               JOptionPane.showMessageDialog(null, "Sửa thất bại!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
           }
       }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
      // xóa hóa đơn
       if(JtablePN.getSelectedRow() == -1)
       {
           JOptionPane.showMessageDialog(null, "Vui lòng chọn thông tin muốn xóa!", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
       }
       else
       {
           int reply = JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn xóa phiếu này?","Xóa phiếu nhập",JOptionPane.WARNING_MESSAGE);
           if(reply == JOptionPane.YES_OPTION){
            //xóa pn     
            if(BUSQLPHIEUNHAP.getInstance().Delete(mapn))
           {
               JOptionPane.showMessageDialog(null, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
               btnSearchActionPerformed(evt);
           }
           else{
               JOptionPane.showMessageDialog(null, "Xóa thất bại!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
           }  
        }
       }
    }//GEN-LAST:event_btnXoaActionPerformed

    public void LoadCTPN(int mapn)
    {
        Tongtien = 0;
        tableModelCT.setRowCount(0);
       
        alrowCT = BUSQLPHIEUNHAP.getInstance().SearchCT(mapn);
      
        if (alrowCT != null) {
            Object count = 1;
            for (int i = 0; i < alrowCT.size(); i++) {
                String rows[] = new String[5];
                rows[0] = count.toString();                      //STT
                rows[1] = alrowCT.get(i)[0];                     //MaSP
                rows[2] = alrowCT.get(i)[1];                     //TenSP
                rows[3] = alrowCT.get(i)[2];                     //SLNHAP
                int sl = Integer.parseInt(alrowCT.get(i)[2]);
                float dg = Float.parseFloat(alrowCT.get(i)[3]);
                Object tt = sl * dg;
                rows[4] = tt.toString();                         //Tổng tiền
                tableModelCT.addRow(rows);
                //mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update lại trên frame
                count = (int)count + 1;
                Tongtien += (float)tt;
            }
        }
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
                //thêm cthd
        isShowing = true;
       ThemCTPN formThemCTPN = new ThemCTPN();
       formThemCTPN.addWindowListener( new WindowAdapter() {
                    @Override
                    public void windowClosed(WindowEvent we) {
                        LoadCTPN(mapn);
                        isShowing = false;
                        if(BUSQLPHIEUNHAP.getInstance().UpdateTT(mapn,Tongtien))
                        {
                            JOptionPane.showMessageDialog(null, "Load thành công", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
                        }
                        LoadButton();
                        btnSearchActionPerformed(evt);
                    }
                } );
       LoadButton();
       formThemCTPN.show();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        if (JtableCTPN.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn thông tin muốn xóa!", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int reply = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa?", "Xóa chi tiết phiếu nhập", JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                //xóa cthd    
                int row = JtableCTPN.getSelectedRow();
                int masp = Integer.parseInt(JtableCTPN.getModel().getValueAt(row, 1).toString());
                if (BUSQLPHIEUNHAP.getInstance().DeleteCTPN(mapn, masp)) {
                    JOptionPane.showMessageDialog(null, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    LoadCTPN(mapn);
                    if(BUSQLPHIEUNHAP.getInstance().UpdateTT(mapn, Tongtien))
                        {
                            JOptionPane.showMessageDialog(null, "Load thành công", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
                        }
                        LoadButton();
                    btnSearchActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa thất bại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        // sửa pn
        // sửa hóa đơn
        if (JtableCTPN.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn thông tin muốn sửa!", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int reply = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn sửa?", "Sửa chi tiết hóa đơn", JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                //xóa cthd    
                int row = JtableCTPN.getSelectedRow();
                int masp = Integer.parseInt(JtableCTPN.getModel().getValueAt(row, 1).toString());
                int sl = Integer.parseInt(txbSL.getText());
                if (BUSQLPHIEUNHAP.getInstance().UpdateCTPN(mapn, masp, sl)) {
                    JOptionPane.showMessageDialog(null, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    LoadCTPN(mapn);
                    if(BUSQLPHIEUNHAP.getInstance().UpdateTT(mapn, Tongtien))
                        {
                            JOptionPane.showMessageDialog(null, "Load thành công", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
                        }
                        LoadButton();
                    btnSearchActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(null, "Sửa thất bại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnUpActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
               //tìm kiếm
        tableModelPN.setRowCount(0);
 
        alrow = BUSQLPHIEUNHAP.getInstance().Search(txbSearch.getText());
        
        if (alrow != null) {
            Object count = 1;
            for (int i = 0; i < alrow.size(); i++) {
                String rows[] = new String[7];
                rows[0] = count.toString();                    //STT
                rows[1] = alrow.get(i)[0];                     //MaPN
                rows[2] = alrow.get(i)[1];                     //MANV
                rows[3] = alrow.get(i)[2];                     //TENNV
                rows[4] = alrow.get(i)[3];                     //Ngaylap
                rows[5] = alrow.get(i)[4];                     //NCC
                rows[6] = alrow.get(i)[5];                     //Tổng tiền
                tableModelPN.addRow(rows);
                //mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update lại trên frame
                count = (int)count + 1;
            }
        }
         DisableComponent();
         tableCT();
         ClearCTPN();
         ClearPN();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void JtablePNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtablePNMousePressed
        // TODO add your handling code here:
        int row = JtablePN.getSelectedRow();
        lbMa.setText(JtablePN.getModel().getValueAt(row, 1).toString());
        txbMaNV.setText(JtablePN.getModel().getValueAt(row, 2).toString());
        txbTenNV.setText(JtablePN.getModel().getValueAt(row, 3).toString());
        //dpNgayHD.setDateFormatString(JtableHD.getModel().getValueAt(row, 4).toString());
        cbNCC.setSelectedItem(JtablePN.getModel().getValueAt(row, 5).toString());
        lbTong.setText(JtablePN.getModel().getValueAt(row, 6).toString());

        mapn = Integer.parseInt(alrow.get(row)[0]);
        EnableComponent();
        LoadCTPN(mapn);
    }//GEN-LAST:event_JtablePNMousePressed

    private void JtableCTPNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableCTPNMouseClicked
        int row = JtableCTPN.getSelectedRow();
        this.txbTenSP.setText(JtableCTPN.getModel().getValueAt(row, 2).toString());
        this.txbSL.setText(JtableCTPN.getModel().getValueAt(row, 3).toString());
        this.txbDG.setText(alrowCT.get(row)[3]);
    }//GEN-LAST:event_JtableCTPNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyPhieuNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableCTPN;
    private javax.swing.JTable JtablePN;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnLapPN;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnUp;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbNCC;
    private com.toedter.calendar.JDateChooser dpNgayNhap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbMa;
    private javax.swing.JLabel lbTong;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMaPN;
    private javax.swing.JLabel lblNCC;
    private javax.swing.JLabel lblNgayNhap;
    private javax.swing.JLabel lblQuanLyPN;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblTong;
    private javax.swing.JTextField txbDG;
    private javax.swing.JTextField txbMaNV;
    private javax.swing.JTextField txbSL;
    private javax.swing.JTextField txbSearch;
    private javax.swing.JTextField txbTenNV;
    private javax.swing.JTextField txbTenSP;
    // End of variables declaration//GEN-END:variables
}
